/*
 * Copyright (c) 2015, TypeZero Engine (game.developpers.com)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of TypeZero Engine nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

package org.typezero.gameserver.skillengine.effect;


/**
 * @author kecimis
 *
 */
public enum EffectType {

	ABSOLUTESLOW,
	ABSOLUTESNARE,
	ABSOLUTESTATTOPCBUFF,
	ABSOLUTESTATTOPCDEBUFF,
	ACTIVATEENSLAVE,
	ALWAYSBLOCK,
	ALWAYSDODGE,
	ALWAYSPARRY,
	ALWAYSRESIST,
	APBOOST,
	ARMORMASTERY,
	AURA,
	BACKDASH,
	BIND,
	BLEED,
	BLIND,
	BOOSTDROPRATE,
	BOOSTHATE,
	BOOSTHEAL,
	BOOSTSKILLCASTINGTIME,
	BOOSTSKILLCOST,
	BOOSTSPELLATTACK,
	BUFFBIND,
	BUFFSILENCE,
	BUFFSLEEP,
	BUFFSTUN,
	CANNON,
	CARVESIGNET,
	CASEHEAL,
	CHANGEHATEONATTACKED,
	CLOSEAERIAL,
	CONDSKILLLAUNCHER,
	CONFUSE,
	CONVERTHEAL,
	CURSE,
	DASH,
	DEATHBLOW,
	DEBOOSTHEAL,
	DEFORM,
	DELAYEDFPATKINSTANT,
	DELAYEDSKILL,
	DELAYEDSPELLATTACKINSTANT,
	DISEASE,
	DISPEL,
	DISPELBUFF,
	DISPELBUFFCOUNTERATK,
	DISPELDEBUFF,
	DISPELDEBUFFMENTAL,
	DISPELDEBUFFPHYSICAL,
	DISPELNPCBUFF,
	DISPELNPCDEBUFF,
	DPHEAL,
	DPHEALINSTANT,
	DPTRANSFER,
	DRBOOST,
	DUMMY,
	ESCAPE,
	EVADE,
	EXTENDAURARANGE,
	FALL,
	FEAR,
	FLYOFF,
	FPATTACK,
	FPATTACKINSTANT,
	FPHEAL,
	FPHEALINSTANT,
	HEAL,
	HEALCASTORONATTACKED,
	HEALCASTORONTARGETDEAD,
	HEALINSTANT,
	HIDE,
	HIPASS,
	HOSTILEUP,
	INTERVALSKILL,
	INVULNERABLEWING,
	MAGICCOUNTERATK,
	MOVEBEHIND,
	MPATTACK,
	MPATTACKINSTANT,
	MPHEAL,
	MPHEALINSTANT,
	NODEATHPENALTY,
	NOFLY,
	NOREDUCESPELLATKINSTANT,
	NORESURRECTPENALTY,
	ONETIMEBOOSTHEAL,
	ONETIMEBOOSTSKILLATTACK,
	ONETIMEBOOSTSKILLCRITICAL,
	OPENAERIAL,
	PARALYZE,
	PETORDERUSEULTRASKILL,
	PETRIFICATION,
	POISON,
	POLYMORPH,
	PROCATKINSTANT,
	PROCDPHEALINSTANT,
	PROCFPHEALINSTANT,
	PROCHEALINSTANT,
	PROCMPHEALINSTANT,
	PROCVPHEALINSTANT,
	PROTECT,
	PROVOKER,
	PULLED,
	RANDOMMOVELOC,
	REBIRTH,
	RECALLINSTANT,
	REFLECTOR,
	RESURRECT,
	RESURRECTBASE,
	RESURRECTPOSITIONAL,
	RETURN,
	RETURNPOINT,
	RIDEROBOT,
	ROOT,
	SANCTUARY,
	SEARCH,
	SHAPECHANGE,
	SHIELD,
        MPSHIELD,
	SHIELDMASTERY,
	SIGNET,
	SIGNETBURST,
	SILENCE,
	SIMPLEROOT,
	SKILLATKDRAININSTANT,
	SKILLATTACKINSTANT,
	SKILLCOOLTIMERESET,
	SKILLLAUNCHER,
	SKILLXPBOOST,
	SLEEP,
	SLOW,
	SNARE,
	SPELLATTACK,
	SPELLATKDRAIN,
	SPELLATKDRAININSTANT,
	SPELLATTACKINSTANT,
	SPIN,
	STAGGER,
	STATBOOST,
	STATDOWN,
	STATUP,
	STUMBLE,
	STUN,
	SUBTYPEBOOSTRESIST,
	SUBTYPEEXTENDDURATION,
	SUMMON,
	SUMMONBINDINGGROUPGATE,
	SUMMONFUNCTIONALNPC,
	SUMMONGROUPGATE,
	SUMMONHOMING,
	SUMMONHOUSEGATE,
	SUMMONSERVANT,
	SUMMONSKILLAREA,
	SUMMONTOTEM,
	SUMMONTRAP,
	SWITCHHOSTILE,
	SWITCHHPMP,
	TARGETTELEPORT,
	WEAPONSTATBOOST,
	WEAPONSTATUP,
	WEAPONDUAL,
	WEAPONMASTERY,
	XPBOOST;
}
