/*
 * Copyright (c) 2015, TypeZero Engine (game.developpers.com)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of TypeZero Engine nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */


package org.typezero.gameserver.model.account;

import org.typezero.gameserver.model.Race;
import org.typezero.gameserver.model.items.storage.Storage;

import java.sql.Timestamp;
import java.util.*;

/**
 * This class represents game account and is holding such informations as:
 * <ul>
 * <li>account id</li>
 * <li>account name</li>
 * <li> {@link AccountTime account time info}</li>
 * <li>a list of {@link PlayerAccountData} objects each of which keeping information about player that must be available
 * on character selection screen.</li>
 * </ul>
 *
 * @author SoulKeeper
 * @modified cura
 */
public class Account implements Iterable<PlayerAccountData> {

	/** Unique id of this account (it's generated by login server) */
	private int id;
	/** Unique name of this account */
	private String name;
	/**
	 * Access level
	 */
	private byte accessLevel;
	/**
	 * Membership of this account
	 */
	private byte membership;

	private AccountTime accountTime;

	private Map<Integer, PlayerAccountData> players = new HashMap<Integer, PlayerAccountData>();

	private Storage accountWarehouse;

	private int numberOfAsmos = 0;

	private int numberOfElyos = 0;

	private CharacterPasskey characterPasskey;

	private String securityToken = "";

	public String getSecurityToken() {
		return securityToken;
	}

	public void setSecurityToken(String token) {
		this.securityToken = token;
	}

	public Account(int id) {
		this.id = id;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public AccountTime getAccountTime() {
		return accountTime;
	}

	public void setAccountTime(AccountTime accountTime) {
		this.accountTime = accountTime;
	}

	/**
	 * @return the accessLevel
	 */
	public byte getAccessLevel() {
		return accessLevel;
	}

	/**
	 * @param accessLevel
	 *          the accessLevel to set
	 */
	public void setAccessLevel(byte accessLevel) {
		this.accessLevel = accessLevel;
	}

	/**
	 * @return the membership
	 */
	public byte getMembership() {
		return membership;
	}

	/**
	 * @param membership
	 *          the membership to set
	 */
	public void setMembership(byte membership) {
		this.membership = membership;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}

		if (!(o instanceof Account)) {
			return false;
		}

		Account account = (Account) o;

		return id == account.id;
	}

	@Override
	public int hashCode() {
		return id;
	}

	/**
	 * @param chaOid
	 * @return PlayerAccountData
	 */
	public PlayerAccountData getPlayerAccountData(int chaOid) {
		return players.get(chaOid);
	}

	/**
	 * @param accPlData
	 */
	public void addPlayerAccountData(PlayerAccountData accPlData) {
		players.put(accPlData.getPlayerCommonData().getPlayerObjId(), accPlData);
		switch (accPlData.getPlayerCommonData().getRace()) {
			case ASMODIANS:
				numberOfAsmos++;
				break;
			case ELYOS:
				numberOfElyos++;
				break;
		}
	}

	/**
	 * @return the accountWarehouse
	 */
	public Storage getAccountWarehouse() {
		return accountWarehouse;
	}

	/**
	 * @param accountWarehouse
	 *          the accountWarehouse to set
	 */
	public void setAccountWarehouse(Storage accountWarehouse) {
		this.accountWarehouse = accountWarehouse;
	}

	/**
	 * @return the characterPasskey
	 */
	public CharacterPasskey getCharacterPasskey() {
		if (characterPasskey == null)
			characterPasskey = new CharacterPasskey();
		return characterPasskey;
	}

	/** Returns the number of players that are on this account */
	public int size() {
		return players.size();
	}

	/**
	 * Sorts the accounts on last online.
	 */
	public ArrayList<PlayerAccountData> getSortedAccountsList() {
		ArrayList<PlayerAccountData> list = new ArrayList<PlayerAccountData>();
		list.addAll(players.values());
		Collections.sort(list, new Comparator<PlayerAccountData>() {

			@Override
			public int compare(PlayerAccountData x, PlayerAccountData y) {
				Timestamp t1 = x.getPlayerCommonData().getLastOnline();
				Timestamp t2 = y.getPlayerCommonData().getLastOnline();
				if (t2 == null)
					return 1;
				else if (t1 == null)
					return -1;
				return y.getPlayerCommonData().getLastOnline().compareTo(x.getPlayerCommonData().getLastOnline());
			}
		});
		return list;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Iterator<PlayerAccountData> iterator() {
		return players.values().iterator();
	}

	public int getNumberOf(Race race) {
		switch (race) {
			case ASMODIANS:
				return numberOfAsmos;
			case ELYOS:
				return numberOfElyos;
		}
		return 0;
	}

	public void decrementCountOf(Race race) {
		switch (race) {
			case ASMODIANS:
				numberOfAsmos--;
				break;
			case ELYOS:
				numberOfElyos--;
				break;
		}
	}

	private long tollCount;

	public void setToll(long toll) {
		tollCount = toll;
	}

	public long getToll() {
		return tollCount;
	}

	public boolean isEmpty() {
		return numberOfAsmos == 0 && numberOfElyos == 0;
	}

	public int getMaxPlayerLevel() {
		int maxLevel = 1;
		for (PlayerAccountData pad : players.values()) {
			if (pad.getPlayerCommonData().getLevel() > maxLevel) {
				maxLevel = pad.getPlayerCommonData().getLevel();
			}
		}
		return maxLevel;
	}

	@Override
	public String toString() {
		return "Account [id=" + id + ", name=" + name + "]";
	}
}
